### ISSUE TITLE
Server receving new connections but not able to log into the game

### ISSUE THREAD

**Issue by valentino-defelice** [Ruk33/l2auth#13]
Hey Buddy, how are you? This project looks really interesting, I just wanted to check with you if this is working on your side, since I'm testing it in my local, I could set up everything, but when I'm trying to log into the game, server receive the petition but is not logging.

I'm executing it in Linux environment.

Regards,
Valentino.

**Comment by Ruk33** [comment]
Hey Valentino, when you enter your username and password, do you have a response? If not, make sure to update your l2.ini or host file so it points to your server.

**Comment by Ruk33** [comment]
As an additional note, if I recall correctly, I believe there was an issue with the IPs.
If 127.0.0.1 doesn't work (in the project's config), try using 0.0.0.0

**Comment by Ruk33** [comment]
Tested on Windows it's working fine.

![image](https://github.com/Ruk33/l2auth/assets/1719111/6067d241-d9a6-464e-ab5a-988155b09411)

**Comment by Ruk33** [comment]
Alright, was able to review in Linux and there was an issue. The directory
where the information is saved was being created with incorrect permissions.

Fixed in https://github.com/Ruk33/l2auth/commit/2e4f8a4c281e4646123cbae97423f7061edfa3e8

Will close, but feel free to re-open if you still have issues.
Thanks!

EDIT: To fix it on your end, you will have to

- Delete the `data` folder in `bin`
- Recompile with `bash build.sh`
- That's it, run the login server and the game server
